### ISSUE TITLE
Why setHtml(String content) move cursor to first position?

### ISSUE THREAD

**Issue by praveenbbhati** [wasabeef/richeditor-android#115]
Hi,
In onTextChange() method i'm changing content and use setHtml() method but all the time, it's moving cursor to first position. May i know why this is happening?

**Comment by shahzadakram67** [comment]
try this after setHtml()
                mEditor.clearFocusEditor();
                mEditor.focusEditor();

**Comment by liuchenc** [comment]
After sethhtml (), clicking the undo button is invalid. How to resolve it
