### ISSUE TITLE
Text alignment (Justify)

### ISSUE THREAD

**Issue by glaucioleonardo** [wasabeef/richeditor-android#116]
Hello! How can I justify the text?

**Comment by glaucioleonardo** [comment]
I got how to Justify the text...
1. Add a Button to your toolbar;
2. add the onClick event listener;
3. In the class Rich Editor just add the following method:

`public void setJustifyFull() {
    exec("javascript:RE.setJustifyFull();");
  }`

4. In the rich_editor.js add the following code
`if (document.queryCommandState('JustifyFull')) {
        items.push('**JustifyFull**');
    }`
Important: The letter J and F must be in cap mode. It was not working using like this jusfityFull, justifyfull,...

**Comment by rwmobi** [comment]
@wasabeef , are there any reasons for this not being provided in master branch?

I see this is already half done in the code.

richeditor/src/main/assets/rich_editor.js
`
if (document.queryCommandState('justifyFull')) {
items.push('justifyFull');
}
`

 Seems we just need to add setJustifyFull() {..}?

Thanks!
