### ISSUE TITLE
Can not input "+"

### ISSUE THREAD

**Issue by chinnkou** [wasabeef/richeditor-android#118]
I can't input "+", and found the below code in rich_editor.js

> RE.setHtml = function(contents) {
    RE.editor.innerHTML = decodeURIComponent(contents.replace(/\+/g, '%20'));
}

why replace "+"?

**Comment by DushyantMainwal** [comment]
@chinnkou Did you found any solution for that?

**Comment by chinnkou** [comment]
@DushyantMainwal 
Yes, now I use the RE.editor.innerHTML. It can support the '+'.

 RE.callback = function() {
     window.location.href = "re-callback://" + encodeURI(RE.getHtml());
    RichEditor.setInnerHTML(RE.getHtml());
 }
  
 RE.setHtml = function(contents) {
     RE.editor.innerHTML = decodeURIComponent(contents.replace(/\+/g, '%20'));
     RichEditor.setInnerHTML(RE.getHtml());
 }
  
 RE.getHtml = function() {
    return RE.editor.innerHTML;
}

**Comment by methodForLife** [comment]
@chinnkou Hi, could you please make your explain more specific? I am a new bee and unfamiliar with javascript. Am I supposed to extend the RichEditor.java? And add a `rich_editor.js` in my project? Thank you in advance:)

**Comment by shahzadakram67** [comment]
kindly can you explain it
