### ISSUE TITLE
Automatically Convert Links to Hyperlink

### ISSUE THREAD

**Issue by searchy2** [wasabeef/richeditor-android#119]
Currently, URL links are not hyperlinked. It would be great if URLs were clickable. 
Setting the following code in HTML does not work:
```
        android:linksClickable="true"
        android:autoLink="web|email"
```

Is there a way to automatically make hyperlinks clickable or is that not a feature?

**Comment by searchy2** [comment]
Closing for now.

**Comment by fukemy** [comment]
how did u solved this?

**Comment by wobo-swati** [comment]
Is this issue resolved ?  I am still facing same issue - hyperlinks are not clickable.
