### ISSUE TITLE
Append text into cursor position

### ISSUE THREAD

**Issue by Luiz-Otavio-Dorigon** [wasabeef/richeditor-android#138]
Would it be possible to add text at the cursor position?

For example, adding a button that clicks adds standard text.

**Comment by 330939204** [comment]
use the js funtion insertHtml

create a class that extends the RichEditor

add method

`public void insertHtml(String content) {
    exec("javascript:RE.prepareInsert();");
    exec("javascript:RE.insertHTML('" + content + "');");
  }`

**Comment by Luiz-Otavio-Dorigon** [comment]
Thank you, it worked perfectly.

**Comment by OnlyMyRailgun** [comment]
@330939204 Thank you for your excellent resolving. But I still have a problem, when I call insertHtml("abc"), it worked perfectly. But if I call insertHtml("<br>"), it didn't work. Can you give some help?
