### ISSUE TITLE
String resource app_name

### ISSUE THREAD

**Issue by micHar** [wasabeef/richeditor-android#17]
You have <string name="app_name">richeditor</string> in your resources. It's overriding the default app_name used in most android projects. It is probably not used in your code anyway, so should be removed, or renamed to have a prefix like jpre__app_name otherwise.

**Comment by micHar** [comment]
I appears to work without this default string. I created pull request for this issue https://github.com/wasabeef/richeditor-android/pull/18. It would be great if you could merge it and put 0.2.1 in jcenter. 

Thanks for an awesome lib btw :)

**Comment by wasabeef** [comment]
@micHar 

v0.2.2 relased
