### ISSUE TITLE
Can't remove format

### ISSUE THREAD

**Issue by nastyanick** [wasabeef/richeditor-android#21]
Add please command for format removing

**Comment by ray1984** [comment]
@wasabeef Please check and approve https://github.com/wasabeef/richeditor-android/pull/22

**Comment by wasabeef** [comment]
@ray1984 
thanks.

**Comment by ray1984** [comment]
@wasabeef When will you release 0.3.0?

**Comment by wasabeef** [comment]
@ray1984 

i will release in this weekend.

**Comment by wasabeef** [comment]
@nastyanick  @ray1984 

Hi. I was released.

try `0.3.0`

thanks.

**Comment by ray1984** [comment]
@wasabeef Sorry, but my code isn't working. I sent you fix - https://github.com/wasabeef/richeditor-android/pull/24
