### ISSUE TITLE
editor to be scrollable

### ISSUE THREAD

**Issue by ShankyPatel** [wasabeef/richeditor-android#221]
is there any way to scroll the editor, just like textview can be scrollable. I want the editor height to be fixed and should be able to scroll the content.

**Comment by FiratGURGUR** [comment]
I have the same problem

**Comment by ShankyPatel** [comment]
did u find any solution ? @FiratGURGUR

**Comment by ShankyPatel** [comment]
hi @FiratGURGUR it do scrolls the content, just make sure if the editor is not inside any scrollview. I removed the parent scrollview and scroll works now.

**Comment by ShankyPatel** [comment]
got the solution.
