### ISSUE TITLE
Soft Keyboard not showing on android 9 and android R

### ISSUE THREAD

**Issue by mbenyoub** [wasabeef/richeditor-android#229]
The layout is inflated correctly but when we try to type some text the soft-keyboard doesn't show up

Tested on real tablet on android 9 , and on emulator android R.
[version 1.2.2]

**Comment by mbenyoub** [comment]
Sorry, this issue is not correct , please ignore it. (the editor was disabled)

**Comment by vikas-jain-plutus** [comment]
Can you please tell me how to enable the editor after loading the data?
