### ISSUE TITLE
Unable to change default text color in RichEditor

### ISSUE THREAD

**Issue by Bluepies** [wasabeef/richeditor-android#23]
The color change button works to change a span, but I want the default color to be something other than black - my app has a dark background. There is not an obvious way to do this. Is there something I'm missing, or does this feature need to be added? I'm a newcomer to Java.

**Comment by wasabeef** [comment]
@Bluepies 

Hi, we supported it. in `0.3.0`

try it.
```
editor.setEditorFontColor(Color.RED);
```
