### ISSUE TITLE
Please update to new version 

### ISSUE THREAD

**Issue by chrissd23** [wasabeef/richeditor-android#38]
Hi, 

Is it possible to upload the latest version to jcenter ?  

It would be nice , because i would like to use list elements :)

**Comment by wasabeef** [comment]
@chrissd23 
Hi,
It has been released.  :shipit:

**Comment by chrissd23** [comment]
Thanks :+1:  @wasabeef

**Comment by chrissd23** [comment]
So I can use this dependency compile 'jp.wasabeef:richeditor-android:1.1.0'  ?

**Comment by chrissd23** [comment]
It works ;)
