### ISSUE TITLE
Disable Input Mode

### ISSUE THREAD

**Issue by FabioConsonni** [wasabeef/richeditor-android#79]
Hi!

I’m using your RichText Editor and it is beautiful!

Please I have a question: is it possible to disable the input mode? I would like to present the page as read-only and the user has to unlock the page to edit it.

Thanks in advance,

Fabio.

**Comment by ParitoshBh** [comment]
Hey!

Did you manage to get the disable part working?

**Comment by swilkinson1** [comment]
I've had luck disabling input using 'editor.setFocusable(false);'

**Comment by FabioConsonni** [comment]
I used a simple webview in case of readonly, but I think that @swilkinson1 suggest should works.
